### ISSUE TITLE
Access Github npm package information via API.

### ISSUE THREAD

**Issue by jecorte** [Joedahms/Software-Engineering-Project#31]
Figure out how to access packages, and provide information from those packages. This includes:

- [x] Total commits, open/closed issues, ratio of opened to closed. (how many commits are done in a certain time period? How recent?)
- [x] Length of comments on issues.
- [x] License documentation (accessing the README)
- [x] Number of forks, starts and contributors (how many key contributors are there?)
- [x] Lifetime of project (date of creation - last commit)
 
Check something off of the list when you have it working, and commit it to the branch I'll create for this issue.

**Comment by Joedahms** [comment]
#35

**Comment by Joedahms** [comment]
#50

**Comment by jecorte** [comment]
Finished switching everything. Onto metric calculations.
